default: &default
  adapter: postgresql
  encoding: unicode
  username: clecotech
  password: clecotech
  pool: 30
  host: localhost
development:
  <<: *default
 
  database: socialapp_development
  
test:
  <<: *default
  database: socialapp_test

production:
  <<: *default
  database: socialapp_production